NVSHAS-9590 To choose which vulnerability score for all assets.
neuvector/manager pull request #795
Opened 2024-12-13 18:34 UTC by lsongsuse

This PR introduces a feature that allows users to select a specific vulnerability score to be used for all assets (Platform, Nodes, Container, Registry).

Changes:

- A dropdown (or equivalent) has been added to the UI for score selection

![Select_Vulnerability_Score_for_All_Assets](https://github.com/user-attachments/assets/884deb49-d4f8-403c-a49c-57044665f7f4)

2024-12-13 19:25 UTC, BinX-Suse approved these changes
LGTM.

2024-12-13 22:40 UTC, xingzhang-suse requested changes
<img width="1728" alt="Screenshot 2024-12-13 at 2 37 22 PM" src="https://github.com/user-attachments/assets/368db87f-fb3a-4ccc-b5bb-17f87e49f395" />
<img width="1728" alt="Screenshot 2024-12-13 at 2 37 55 PM" src="https://github.com/user-attachments/assets/57692916-3573-4026-b7b0-9861baa1b781" />
The filter text box was pushed out of the panel

2024-12-14 03:04 UTC, lsongsuse commented
Fixed the UI alignment issue in the Node and Container pages.

![container page](https://github.com/user-attachments/assets/07b357d8-0d91-494e-bcde-a5c65b04a0b7)
![node page](https://github.com/user-attachments/assets/57605b53-e4b4-47b7-9bd7-604b4b697f79)

2024-12-14 03:12 UTC, xingzhang-suse approved these changes

2024-12-14 03:12 UTC, merged